# Generated by Django 2.2.28 on 2024-11-18 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='team',
            new_name='robe',
        ),
        migrations.RemoveField(
            model_name='character',
            name='type',
        ),
    ]
