# Generated by Django 2.2.28 on 2024-11-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_auto_20241118_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='photo',
            field=models.ImageField(upload_to='characters/'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='photo',
            field=models.ImageField(upload_to='equipements/'),
        ),
    ]
