# Generated by Django 2.2.28 on 2024-11-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_auto_20241119_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='texte',
            field=models.CharField(default='oui', max_length=200),
            preserve_default=False,
        ),
    ]
